### ISSUE TITLE
VEP error

### ISSUE THREAD

**Issue by androidpifu** [ylab-hi/ScanNeo2#38]
When I was running ScanNeo2, several samples encountered errors during the VEP annotation process, specifically for the main task of SNVs. The following error occurred for all of them. 
localrule annotate_variants:
    input: results/R22025/variants/somatic.snvs.vcf.gz, results/R22025/variants/somatic.snvs.vcf.gz.tbi, resources/refs/genome.fasta, resources/vep/cache, resources/vep/plugins
    ```
output: results/R22025/annotation/somatic.snvs.vcf, results/R22025/annotation/somatic.snvs.html
    log: logs/vep/R22025_somatic.snvs_annotate.log
    jobid: 2
    reason: Missing output files: results/R22025/annotation/somatic.snvs.vcf; Input files updated by another job: results/R22025/variants/somatic.snvs.vcf.gz.tbi, results/R22025/variants/somatic.snvs.vcf.gz
    wildcards: sample=R22025, vartype=somatic.snvs
    threads: 4
    resources: tmpdir=/tmp

Traceback (most recent call last):
  File "/mnt/work/zhumc/software/ScanNeo2/ScanNeo2/.snakemake/scripts/tmp_6vhvqtx.wrapper.py", line 68, in <module>
    shell(
  File "/home/zhumc/.conda/envs/scanneo2/lib/python3.12/site-packages/snakemake/shell.py", line 297, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  (bcftools view 'results/R22025/variants/somatic.snvs.vcf.gz' | vep --everything --fork 4 --format vcf --vcf --offline --cache --dir_cache resources/vep/cache --cache_version 111 --species homo_sapiens --assembly GRCh38  --fasta resources/refs/genome.fasta --dir_plugins resources/vep/plugins --plugin NMD, --plugin Wildtype, --plugin Downstream, --output_file STDOUT --stats_file results/R22025/annotation/somatic.snvs.html | bcftools view -Ov > results/R22025/annotation/somatic.snvs.vcf)  2> logs/vep/R22025_somatic.snvs_annotate.log' returned non-zero exit status 255.
RuleException:
CalledProcessError in file /mnt/work/zhumc/software/ScanNeo2/ScanNeo2/workflow/rules/annotation.smk, line 70:
Command 'set -euo pipefail;  /home/zhumc/.conda/envs/scanneo2/bin/python3.12 /mnt/work/zhumc/software/ScanNeo2/ScanNeo2/.snakemake/scripts/tmp_6vhvqtx.wrapper.py' returned non-zero exit status 1.
```
Could you please provide some assistance?

**Comment by riasc** [comment]
Hi, thanks for reporting this. Could you please provide me with the `logs/vep/R22025_somatic.snvs_annotate.log` file? It should give us more information about what went wrong.

Thanks

**Comment by androidpifu** [comment]
Unfortunately, there are no entries in the log file.
[R22025_somatic.snvs_annotate.log](https://github.com/user-attachments/files/16924233/R22025_somatic.snvs_annotate.log)

**Comment by riasc** [comment]
Ok, thanks. 

Could you please verify that the plugins for VEP have been downloaded? And print the content of the folder `resources/vep/plugins`. It looks like these have not been downloaded correctly. These should contain: `Downstream.pm`, `NMD.pm`, and `Wildtype.pm`

Could you also check if the SNV Vcf file is correct (e.g., bcftools view 'results/R22025/variants/somatic.snvs.vcf.gz') as this is getting piped to VEP. Could be that this causes some issues already. As I understand this happens to multiple samples?

**Comment by androidpifu** [comment]
Thank you for your suggestion. The SNV VCF file format is correct, I have tested it. The contents of the resources/vep/plugins folder are complete, and my SNV VCF contains only one sample.
![捕获](https://github.com/user-attachments/assets/8ac66e32-2bbe-4ed6-acd1-1e0d61bf3bf2)

**Comment by androidpifu** [comment]
I encounter the following error when executing the command below:
 `bcftools view 'results/R22031/variants/somatic.snvs.vcf.gz' | vep --everything --fork 4 --format vcf --vcf --offline --cache --dir_cache resources/vep/cache --cache_version 111 --species homo_sapiens --assembly GRCh38  --fasta resources/refs/genome.fasta --dir_plugins resources/vep/plugins --plugin NMD, --plugin Wildtype, --plugin Downstream, --output_file STDOUT --stats_file results/R22031/annotation/somatic.snvs.html | bcftools view -Ov > results/R22031/annotation/somatic.snvs.vcf  2> logs/vep/R22031_somatic.snvs_annotate.log`
ERROR：
`Can't use an undefined value as an ARRAY reference at /home/zhumc/.conda/envs/scanneo2/share/ensembl-vep-88.9-0/Bio/EnsEMBL/Funcgen/BindingMatrix.pm line 501.`

**Comment by riasc** [comment]
Hello,
I can't reproduce this error.. could you maybe provide me the SNV file (or part of it)? Thanks

**Comment by androidpifu** [comment]
I tried removing the parameter `--everything`  and then the exception doesn't appear

**Comment by riasc** [comment]
Ok thanks for reporting this. It runs through without `--everything`? Need to test this. Thanks

**Comment by androidpifu** [comment]
Unfortunately，my SNV file is too large and can not be uploaded.

**Comment by riasc** [comment]
Hi — thanks for the report and the dig into `--everything`.

The crash is a **VEP version / cache mismatch**, not a workflow bug. The trace path is the giveaway:

\`\`\`
.../scanneo2/share/ensembl-vep-88.9-0/Bio/EnsEMBL/Funcgen/BindingMatrix.pm
\`\`\`

That's **ensembl-vep 88.9** — a five-year-old binary — running against the v111 cache configured by \`reference.release: 111\`. \`BindingMatrix.pm\` sits behind VEP's \`--regulatory\` codepath (enabled by the \`--everything\` flag the rule passes), and a cache produced by a much newer VEP lays its regulatory motif data out in a way the 88.9 perl code can't traverse — it ends up dereferencing fields that aren't there, and you get the "ARRAY reference" panic.

Dropping \`--everything\` makes the symptom go away because it also turns off \`--regulatory\` — but the underlying mismatch is still there and would resurface on any other regulatory or version-sensitive feature.

The proper fix is to make sure the wrapper's pinned VEP binary is what executes. The \`annotate_variants\` rule uses \`wrapper: "v5.9.0/bio/vep/annotate"\`, which ships its own \`environment.yaml\` pinning a known-good VEP version. The path in your trace (`~/.conda/envs/scanneo2/share/...` rather than `.snakemake/conda/<hash>/share/...`) suggests the wrapper env isn't being honoured — likely because the run wasn't invoked with conda env isolation, so a stale `vep` in your main `scanneo2` env got picked up instead.

**Try one of:**

\`\`\`bash
# Re-run with conda env isolation (so the wrapper's pinned VEP is used):
snakemake --sdm conda ...   # or --use-conda on older snakemake versions

# OR drop the stale VEP from your main env and let the wrapper recreate cleanly:
mamba remove -n scanneo2 ensembl-vep
\`\`\`

The wrapper env materialises at \`.snakemake/conda/<hash>/\` on the next run; once the VEP binary version matches the cache (\`reference.release: 111\`), the regulatory codepath stops crashing. Keeping \`--everything\` is fine — it's needed for the \`SYMBOL\` field, and the regulatory annotations it adds may be useful if you ever want to look at non-coding variants downstream.

Closing — happy to reopen if the conda-isolation step doesn't help.
