### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by Donbbit** [ylab-hi/ScanNeo2#41]
Thank you for writing such an excellent pipeline. I was using it and reached the final step to generate the neoantigen results when I run:
python workflow/scripts/prioritization/compile.py  \   
--SNV "results/test/annotation/somatic.snvs.vcf"   \        
--indels "results/test/annotation/somatic.short.indels.vcf"  \         
--long_indels "results/test/annotation/long.indels.vcf"    \       
--exitrons "results/test/annotation/exitrons.vcf"    \       
--altsplicing "results/test/annotation/altsplicing.vcf"   \        
--fusions "results/test/rnaseq/genefusion/rna_tumor_fusions.tsv"   \        
--custom ""   \        
--proteome resources/refs/peptide.fasta     \      
--anno resources/refs/genome_tmp.gtf      \     
--confidence medium   \        
--mhc_class I   \        
--mhcI "results/test/hla/mhc-I.tsv"    \       
--mhcI_len "8,9,10,11"   \        
--mhcII ""    \       
--mhcII_len "13,14,15"   \        
--counts "results/test/quantification/allcounts.txt"   \        
--threads 8  \        
--output_dir results/test/prioritization     \     
--reference resources/refs/genome.fasta > logs/prioritization/test.log 2>&1

I got the error in the log:
Traceback (most recent call last):
  File "/hsfscqjf1/ST_CQ/P24Z32300N0028/lvmeiqi/pipe_test/scanneo2/workflow/scripts/prioritization/compile.py", line 151, in <module>
    main()
  File "/hsfscqjf1/ST_CQ/P24Z32300N0028/lvmeiqi/pipe_test/scanneo2/workflow/scripts/prioritization/compile.py", line 120, in main
    comp = Compile(options)
           ^^^^^^^^^^^^^^^^
  File "/hsfscqjf1/ST_CQ/P24Z32300N0028/lvmeiqi/pipe_test/scanneo2/workflow/scripts/prioritization/compile.py", line 23, in __init__
    self.prioritize(options.indels, options, "somatic.short.indels")
  File "/hsfscqjf1/ST_CQ/P24Z32300N0028/lvmeiqi/pipe_test/scanneo2/workflow/scripts/prioritization/compile.py", line 49, in prioritize
    vars = variants.Variants(inputfile, options, vartype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hsfscqjf1/ST_CQ/P24Z32300N0028/lvmeiqi/pipe_test/scanneo2/workflow/scripts/prioritization/variants.py", line 125, in __init__
    wt_aa_change, mt_aa_change = self.determine_aa_change(aa_change)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hsfscqjf1/ST_CQ/P24Z32300N0028/lvmeiqi/pipe_test/scanneo2/workflow/scripts/prioritization/variants.py", line 196, in determine_aa_change
    wt_aa_change, mt_aa_change = aa_change.split('/')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

I think the error may be caused by results/test/annotation/somatic.short.indels.vcf But when I checked the results of this file, I couldn't find any issues. The first 200 lines of this file is attached.
[somatic.short.indels_head200.vcf.txt](https://github.com/user-attachments/files/18207982/somatic.short.indels_head200.vcf.txt)

I really appreciate any help.

**Comment by riasc** [comment]
Hi,

sorry I missed this issue. I will look into this on the weekend. I see that you applied it directly on the script. Have you generated this VCF by yourself? The thing is that ScanNeo2 annotates the VCF using 'Variant Effect Predictor'. It seems like the VCF hasn't been annotated.

**Comment by riasc** [comment]
No it has been annotated. Will look into it. Thanks
